### ISSUE TITLE
Verification Feature Request

### ISSUE THREAD

**Issue by callumok2004** [ModuloBot/Tracker#16]
**Is your feature request related to a problem? Please describe.**
No it is not.

**Describe the solution you'd like**
I wan't to be able to have the bot remove a role on verification as well as adding one

**Describe alternatives you've considered**
so far ive used the @everyone role but that is to much work

**Additional context**
No Other Conext

**Comment by NovusTheory** [comment]
Sorry but this feature will not be implemented. Please continue using the everyone role as the designated "unverified" role as that is considered best practice.
