### ISSUE TITLE
Modulo's verification system not working.

### ISSUE THREAD

**Issue by detectiveG** [ModuloBot/Tracker#19]
**Describe the bug**
Modulo is not giving new users the Verified role after they verified.

**To Reproduce**
1.I setup a verification system and made it so another bot DMs a new user upon joining the server to verify themselves using the verification link.
2. New users joined and tried to verify themselves
3. They verified themselves but didn't get the Verified role.
**Expected behavior**
I expected the bot to give the Verified role.

**Screenshots**

**Additional context**
When I tested the verification system using my bots, only one of my ALTs got verified but the rest didn't.

**Comment by NovusTheory** [comment]
Modulo properly gives the verified role. If it can't give the role a message will be shown to the user. Permissions and hierarchy is a common problem. Another issue is the wrong account is used on the website. Make sure all of this is checked and it should work fine

**Comment by NovusTheory** [comment]
Issue resolved based on the official Discord chat
