### ISSUE TITLE
Enabling NameChange tracking in Logging doesn't stick

### ISSUE THREAD

**Issue by VickyTheDemon** [ModuloBot/Tracker#21]
**Describe the bug**
If you have NameChange tracking disabled in Logging on the Dashboard and change it to enabled, the toggle will update on the dashboard but if you log out and back in the change will not stick and it will revert back to disabled. It also will not track on the Discord itself.

**To Reproduce**
1. Go to Dashboard
2. Go to Logging
3. Enable Namechange and click save
4. Log out of the dashboard and log back in
5. Go to Logging and see that Namechange has been disabled again

**Expected behavior**
Namechange toggle should stick when saved and start recording changes on the server.

**Comment by NovusTheory** [comment]
Huh, I actually never noticed that. How long has that been up there o_O. This is actually a feature that was never enabled in the bot at all. Must've accidentally pushed an update to the page which added that when it wasn't supposed to

This issue has been corrected and it no longer shows this as an option in logging. This will be a feature later down the road

**Comment by VickyTheDemon** [comment]
Been there a few months at least I think? Not really sure to be honest.

**Comment by NovusTheory** [comment]
Kind of surprised I never caught onto that nor was it ever reported of not working until now.
