### ISSUE TITLE
More Verifications 

### ISSUE THREAD

**Issue by MarkDuchaney** [ModuloBot/Tracker#24]
**Is your feature request related to a problem? Please describe.**
Limited verifications 

**Describe the solution you'd like**
Have different forms of verification, whether a math problem, answering a question, or just checking a box.

**Comment by NovusTheory** [comment]
The purpose of verification is for bots. I doubt I'll change

**Comment by MarkDuchaney** [comment]
Ok, just a cool idea of different verification.

**Comment by NovusTheory** [comment]
Since I will likely not be changing this since the purpose is for bots I am closing the issue.
