### ISSUE TITLE
An anti-bot system for the levels module.

### ISSUE THREAD

**Issue by EnderSlime123** [ModuloBot/Tracker#26]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A system that would help prevent selfbots/hackers or spambots from leveling up an account.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by NovusTheory** [comment]
Sorry, but this cannot be implemented as it is impossible to detect efficiently. Please inform your servers moderators to watch for spam and if someone decides to cheat the system you may reset their level with `-reset @User`
