### ISSUE TITLE
I am concerned

### ISSUE THREAD

**Issue by SouthenDev** [ModuloBot/Tracker#32]
**Describe the bug**
I do not know why my company anti-virus would say that modulo.xyz is phishing. 

**To Reproduce**
1. Went to get the bot form the dashboard and it said this.

**Expected behavior**
N/A

**Screenshots**
https://cdn.discordapp.com/attachments/610171898365476864/610639682942009349/Screen_Shot_2019-08-12_at_7.54.16_PM.png

**Additional context**

**Comment by NovusTheory** [comment]
This is a false positive and you should have nothing to worry about. Modulo does not do anything malicious.
