### ISSUE TITLE
Redirect after captchat succes

### ISSUE THREAD

**Issue by Beat-YT** [ModuloBot/Tracker#46]
**Is your feature request related to a problem? Please describe.**
the user is a bit lost when they get on the captchat page

**Describe the solution you'd like**
I want to redirect the user when he passes the captcha challenge or an option to close the tab after 3 seconds. Also, an option to change the text of the page before and after successful captchat.

**Comment by NovusTheory** [comment]
What exactly are you looking to achieve? Are you opening the verification page through your own site?

**Comment by Beat-YT** [comment]
no, but i will like to have an option to close the verification captchat tab when they sucessfully complete it
