### ISSUE TITLE
Mentionable Ranks

### ISSUE THREAD

**Issue by vpcatyt** [ModuloBot/Tracker#9]
**Is your feature request related to a problem? Please describe.**
Well, I'm trying to check someone else's rank with Modulo, but it will only show my rank.

**Describe the solution you'd like**
I would like you guys to make the bot so that users are able to see the rank of other users.

**Comment by NovusTheory** [comment]
:tada: This feature has been implemented and currently exists in the beta version of the bot. It will be released to everyone in the future soon.
